---
title: "IntroRmarkdown"
author: "Alli Shields"
date: "10/13/2020"
output: github_document
---

# title
## title
### title

basic text.

*italicize* single astericks

**bold** double astericks

1. make 
2. numbered
3. lists

we can make:

- unumbered
- lists

[link here](https://www.google.com)

#Load Libraries

to add code, make a chunk by clicking (insert > R)
```{r load packages, message=FALSE, warning=FALSE}
library(tidyverse)
library(readxl)
library(lubridate)
#install.packages("RColorBrewer")
```

or by using keyboard shortcuts. on a mac: cmd + alt + i

#Load data

```{r}
socal.fires <- readRDS("~/Desktop/Github/144l_students/Output_Data/Week 1/socal_fires_data.rds")
#socal.fires <- read_csv("~/Desktop/Github/144l_students/Output_Data/Week 1/socal_fires_data.csv")
```

#Look at data

```{r}
glimpse(socal.fires)
```

#Make plot dataframe
```{r}
plot.data <- socal.fires %>% 
  rename(county = County_Unit,
         fire = Fire_Name,
         start = Start_Date,
         end = Controlled_Date,
         acres = Total_Acres_Burned,
         cause = Cause) %>% 
  mutate(county = ifelse(fire == "THOMAS", "VENTURA", county),
         year = year(start))
```

```{r echo = F}
glimpse(plot.data)
```
# Summary Statistics and *group_by()*
